---
name: Check Renovate Config
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: konflux-ci/renovate-config-validator-action@715fae6ea7b656ccefead2dec09ee41d395bee6d # main
        with:
          config_file: .github/renovate.json
